"""fix user review relationship

Revision ID: 1e3d1ab5e603
Revises: d85e5c45fa08
Create Date: 2024-12-30 23:00:07.943289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3d1ab5e603'
down_revision = 'd85e5c45fa08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
